// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evzmzxgqlhnualtyzwpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2em16eGdxbGhudWFsdHl6d3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzMyNDgsImV4cCI6MjA3MTkwOTI0OH0.RimcJG4yjERPyL3wZhnTdBwCRIBbm3679kmVMNFdXLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});